[build]
  base = "projecao-de-eventos"
  command = "npx ng build --configuration production"
  publish = "projecao-de-eventos/dist/projecao-de-eventos/browser"

[[plugins]]
  package = "@netlify/angular-runtime"
